%%
%% This is file `jserror.cls',
%%
%% =============================================
%% IMPORTANT NOTICE:
%% Any modified versions of this file must be renamed
%% with new filenames distinct from jserror.cls.
%% =============================================
%% Copyright 2015 Acetaminophen (@aminophen)
%%
%% -------------------------------------------------
\NeedsTeXFormat{pLaTeX2e}
\ProvidesClass{jserror}
  [2015/05/23 aminophen]
\LoadClass{jsarticle}
\RequirePackage{txfonts}
%%
%% End of file `jserror.cls'.
%%
